# Generated by Django 4.0.4 on 2022-04-29 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myscrap', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='link',
            field=models.CharField(default='', max_length=2083),
        ),
    ]
